env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'svelte3'
overrides:
  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
settings:
  'svelte3/typescript': true
rules:
  '@typescript-eslint/no-empty-function': off # empty functions are used as fallback
  '@typescript-eslint/no-explicit-any': off # will be removed when svelte-check typing is more consistent
