image: node:latest

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - node_modules

before_script:
  - sh ./scripts/banner.sh
  - npm ci --cache .npm --prefer-offline

stages:
  - verify
  - deploy

🔍 Analyse:
  stage: verify
  script:
    - npm run analyse

🧹 Lint:
  stage: verify
  script:
    - npm run lint

🧪 Test:
  stage: verify
  script:
    - npm run test

📦 Deploy:
  stage: deploy
  script:
    - npm run build
    # clone deploy repo and throw away all content but .git/
    - git clone https://github.com/${GITLAB_USER_LOGIN}/${DEPLOY_REPO}.git
    - mv ${DEPLOY_REPO} ${DEPLOY_REPO}-old
    - mkdir ${DEPLOY_REPO}
    - mv -t ${DEPLOY_REPO} ${DEPLOY_REPO}-old/.git
    # add newly built content
    - cp -rf public/* ${DEPLOY_REPO}
    - cd ${DEPLOY_REPO}
    - sed -i "s/href=\"\//href=\"\/${DEPLOY_REPO}\//" index.html
    - sed -i "s/src=\"\//src=\"\/${DEPLOY_REPO}\//" index.html
    - git add .
    # commit and push
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email ${GITLAB_USER_EMAIL}
    - git commit -m ${CI_COMMIT_SHORT_SHA}
    - git push https://${GITLAB_USER_LOGIN}:${DEPLOY_TOKEN}@github.com/${GITLAB_USER_LOGIN}/${DEPLOY_REPO}.git HEAD
  only:
    - main
